packages:
    - packages/*
    - docs

catalog:
    vite: ^5.3.4
    typescript: ^5.5.4
    vue-tsc: ^2.0.29
    eslint: ^9.9.0
    prettier: ^3.3.3
    gitmoji-cli: ^9.4.0

catalogs:
    eslint-config:
        eslint-define-config: ^2.1.0
        eslint-plugin-prettier: ^5.2.1
        eslint-config-prettier: ^9.1.0
        typescript-eslint: ^8.2.0
        eslint-plugin-vue: ^9.27.0
        '@eslint/config-inspector': 0.5.4
    typescript-config:
        '@types/node': ^22.5.0
