packages:
  - packages/*
  - docs

catalog:
  vite: ^5.3.4
  vue: ^3.5.12
  vue-tsc: ^2.1.6
  typescript: ^5.5.4
  tslib: 2.8.1
  eslint: ^9.9.0
  prettier: ^3.3.3
  gitmoji-cli: ^9.4.0

catalogs:
  chalk:
    rollup: 4.28.0
    rollup-plugin-dts: 6.1.1
    '@rollup/plugin-typescript': 12.1.1
    '@rollup/plugin-terser': 0.4.4
    '@rollup/plugin-image': 3.0.3

  browser-data-structure:
    rollup: 4.28.0
    rollup-plugin-dts: 6.1.1
    '@rollup/plugin-typescript': 12.1.1
    '@rollup/plugin-terser': 0.4.4
    '@rollup/plugin-node-resolve': 16.0.0

  eslint-config:
    eslint-define-config: ^2.1.0
    eslint-plugin-prettier: ^5.2.1
    eslint-config-prettier: ^9.1.0
    typescript-eslint: ^8.2.0
    eslint-plugin-vue: ^9.27.0
    '@eslint/config-inspector': 0.5.4

  vue-press:
    vuepress: 2.0.0-rc.18
    vuepress-theme-hope: 2.0.0-rc.59
    sass-embedded: 1.80.3
    flowchart.ts: 3.0.1
    '@vue/repl': 4.4.2
    '@vuepress/bundler-vite': 2.0.0-rc.18
