packages:
    - packages/*
    - docs

catalog:
    vite: ^5.3.4
    vue-tsc: ^2.0.29
    typescript: ^5.5.4
    eslint: ^9.9.0
    eslint-define-config: ^2.1.0
    prettier: ^3.3.3
    eslint-plugin-prettier: ^5.2.1
    eslint-config-prettier: ^9.1.0
    gitmoji-cli: ^9.4.0

catalogs:
    eslint-config:
        eslint-define-config: ^2.1.0
        eslint-plugin-prettier: ^5.2.1
        eslint-config-prettier: '^9.1.0'
